.TH spritz-hash "1" "29 February 2016" "" "Utility"

.SH NAME
spritz-hash \- compute a hash via the spritz streaming cipher

.SH SYNOPSIS
.B spritz-hash
.RB [ \-s
.IR N ]
.RB [ \-h ]
.RI [ file \.\.\.]

.SH DESCRIPTION
spritz-hash computes a cryptographic hash of any
desired size from the input file(s).  A description of 
the hash can be found in 
http://people.csail.mit.edu/rivest/pubs/RS14.pdf.
If no filename is given, or if the filename is '-', 
input is read from \fBstdin\fR.

.SH OPTIONS
.TP
.B \-h 
Display the hash as hex digits instead of base64-encoded.
.TP
.BI \-s " N"
Set the size of the computed hash, in bits. The default is
256 bits. 

.SH EXAMPLES
To get the 128-bit hash of all the c files in the 
directory:
.PP
.nf
.RS
spritz-hash -s128 *.c
.RE
.fi

.SH AUTHOR
Richard Todd (richard@waywardcode.com)

.SH "SEE ALSO"
.BR spritz-crypt (1)

