.TH spritz-crypt "1" "29 February 2016" "" "Utility"

.SH NAME
spritz-crypt \- compute a hash via the spritz streaming cipher

.SH SYNOPSIS
.B spritz-crypt
[\fB\-d\fR] [\fB\-o\fR \fIDIR\fR] [\fB\-p\fR \fIPWD\fR] [\fIfile\fR ...]

.SH DESCRIPTION
spritz-crypt encrypts or decrypts files with the spritz stream
cipher.  A description of the cipher can be found in 
http://people.csail.mit.edu/rivest/pubs/RS14.pdf.
.PP
If no filename is given, or if the filename is '-', 
input is read from \fBstdin\fR.
By default, the output is placed in the same directory as the
input.  The program selects the output filename as follows:
.IP Encrypting:
a ".spritz" extension is added to the original.
.IP Decrypting:
if the input has a ".spritz" extension, remove it. Otherwise,
add an ".unenc" extension. 

.SH OPTIONS
.TP
.B \-d 
Decrypt the input. The default is to encrypt.
.TP
.BI \-o " DIR"
Set the output directory to \fIDIR\fR. The defualt is to place
outputs in the same directory as the inputs.
.TP
.BI \-p " PWD"
Set the passward for encryption/decryption to \fIPWD\fR. 

.SH EXAMPLES
Basic use: encrypt all C files, with password '123', output to the /tmp directory:
.PP
.nf
.RS
spritz-crypt -p 123 -o /tmp  *.c 
.RE
.fi
.PP
spritz-crypt is also useful in pipelines.  To compress and 
encrypt 'file.txt' with password '123':
.PP
.nf
.RS
gzip < file.txt | spritz-crypt -p 123 > out.gz.spritz 
.RE
.fi
.PP
To display the original file.txt contents:
.PP
.nf
.RS
spritz-crypt -d -p 123 < out.gz.spritz | zcat
.RE
.fi

.SH BUGS
The program currently only takes the password on the command line, 
which is a security vulnerability.  It should be enhanced one day
to read the password from the terminal if it's not given.

.SH AUTHOR
Richard Todd (richard@waywardcode.com)

.SH "SEE ALSO"
.BR spritz-hash (1)

